# Docker-compose configuration for production

version: '2.1'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: encuestas_cdmx_cie_django
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-nginx/files/encuestas_cdmx_cie/assets:/files/assets"
            - "/var/log/encuestas_cdmx_cie:/var/log/encuestas_cdmx_cie"
        # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
        #  work.
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: gunicorn encuestas_cdmx_cie.wsgi:application --workers 2 --bind :80
        networks:
            - default
            - encuestas_cdmx_cie_nginx
            - encuestas_cdmx_cie_postgres
        depends_on:
            - redis
        external_links:
            - postgres-12:postgres

    node:
        build:
            context: .
            dockerfile: Dockerfile-node.production
        container_name: encuestas_cdmx_cie_node
        restart: unless-stopped
        command: yarn start
        volumes:
            - "/var/lib/docker-nginx/files/encuestas_cdmx_cie/app/assets:/files/assets"
            - "/var/log/encuestas_cdmx_cie:/var/log/encuestas_cdmx_cie"
        networks:
            - default
            - encuestas_cdmx_cie_nginx

    redis:
        image: redis:4.0.10-alpine
        restart: unless-stopped
        sysctls:
            # To allow maintaining TCP backlog setting that defaults to 511
            net.core.somaxconn: 512
        volumes:
            - "/var/lib/docker-encuestas_cdmx_cie/redis:/data"
        networks:
            - default

# NB: These networks must be created by fabfile and contain the global nginx/postgres containers.
# Keep it in sync with fabfile!
networks:
    default:
        external:
            name: encuestas_cdmx_cie_default
    encuestas_cdmx_cie_nginx:
        external: true
    encuestas_cdmx_cie_postgres:
        external: true
