# Generated by Django 2.2.12 on 2020-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='p6_cantidad',
            field=models.IntegerField(max_length=255),
        ),
    ]
