# Generated by Django 2.2.12 on 2020-04-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20200411_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='p6_cantidad',
            field=models.IntegerField(),
        ),
    ]
